/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Built on */
#define BUILD_DATE "Tue May  6 14:29:33 PDT 2008"

/* Configured on */
#define CONFIGURED_ON "Tue May  6 14:29:33 PDT 2008"

/* Debug */
/* #undef DEBUG */

/* collect nw stats */
#define ENABLE_NETSTAT 1

/* Define to 1 if you have the <atomic.h> header file. */
#define HAVE_ATOMIC_H 1

/* Have BSWAP_ macros */
#define HAVE_BSWAP 1

/* Have libcpc */
#define HAVE_CPC 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Have libkstat */
#define HAVE_LIBKSTAT 1

/* Define to 1 if you have the `ssl' library (-lssl). */
#define HAVE_LIBSSL 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `nanosleep' function. */
#define HAVE_NANOSLEEP 1

/* Define to 1 if you have the <poll.h> header file. */
#define HAVE_POLL_H 1

/* Have sctp */
#define HAVE_SCTP 1

/* Have sendfilev */
#define HAVE_SENDFILEV 1

/* Define to 1 if you have the <siginfo.h> header file. */
#define HAVE_SIGINFO_H 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Have ssl */
#define HAVE_SSL 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/byteorder.h> header file. */
#define HAVE_SYS_BYTEORDER_H 1

/* Define to 1 if you have the <sys/int_limits.h> header file. */
#define HAVE_SYS_INT_LIMITS_H 1

/* Define to 1 if you have the <sys/lwp.h> header file. */
#define HAVE_SYS_LWP_H 1

/* Define to 1 if you have the <sys/poll.h> header file. */
#define HAVE_SYS_POLL_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/varargs.h> header file. */
#define HAVE_SYS_VARARGS_H 1

/* Have udp */
#define HAVE_UDP 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "uperf"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "neel@sun.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "uPerf"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "uPerf 0.2.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "uperf"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.2.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Setting machine os to Linux */
/* #undef UPERF_LINUX */

/* Setting machine os to Solaris */
#define UPERF_SOLARIS 1

/* Have cpu perf counters? */
#define USE_CPC 1

/* Have version1 cpu perf counters? */
/* #undef USE_CPCv1 */

/* Have version2 cpu perf counters? */
#define USE_CPCv2 1

/* Have getrusage */
#define USE_GETRUSAGE 1

/* Version number of package */
#define VERSION "0.2.1"
