name: make check CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install sctp
      run: sudo apt-get install -y libsctp-dev
    - name: insmod sctp
      run: sudo modprobe sctp
    - name: insmod vsock_loopback
      run: sudo modprobe vsock_loopback
    - name: autoreconf
      run: autoreconf -fi
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
